---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: pgbackup
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: "s3://nnhome-pg-backup"
    endpointURL: "https://s3.eu-central-003.backblazeb2.com"
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: aws-access-key-id
      secretAccessKey:
        name: cloudnative-pg-secret
        key: aws-secret-access-key
    wal:
      compression: bzip2
      maxParallel: 8
  retentionPolicy: 30d
