---
name: dexd
services:
  dexd:
    container_name: dexd
    environment:
      DEFAULT_TARGET: 172.16.20.2
      UNIFI_API_KEY: ${UNIFI_API_KEY}
      UNIFI_HOST: https://172.16.1.254
    image: ghcr.io/ishioni/dexd:0.4.4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
