---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-redis
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: authentik-redis
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          automountServiceAccountToken: false
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.10.0
            command:
              - sh
            args:
              - -c
              - >-
                redis-server --requirepass $AUTHENTIK_REDIS__PASSWORD
            env:
              REDIS_PORT: &port 6379
            envFrom:
              - secretRef:
                  name: authentik-redis-secret
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 256M
    service:
      app:
        ports:
          redis:
            enabled: true
            port: *port
