[env]
JUST_UNSTABLE = "1"
FLATE_PATH = '{{config_root}}/kubernetes/flux/cluster'
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = '{{config_root}}/talosconfig'
KUBE_EDITOR = 'nvim'

[settings]
pipx.uvx = true

[tools]
# Pinned for workflows
"actionlint" = "1.7.12"
"github:home-operations/flate" = "v0.6.5"
talos = "1.14.1"
yq = "4.54.1"
# Only used locally
"aqua:astral-sh/uv" = "latest"
"aqua:cilium/hubble" = "latest"
"aqua:google/yamlfmt" = "latest"
"pipx:ansible" = "latest"
"pipx:ansible-core" = "latest"

[hooks]
postinstall = "ansible-galaxy install -r {{config_root}}/ansible/requirements.yaml"

