---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spoolman
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: spoolman-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Application
        SPOOLMAN_DB_TYPE: "postgres"
        SPOOLMAN_DB_HOST: &dbHost "postgres-pgbouncer-rw.database.svc.cluster.local"
        SPOOLMAN_DB_PORT: &dbPort "5432"
        SPOOLMAN_DB_NAME: &dbName "spoolman"
        SPOOLMAN_DB_USERNAME: &dbUser "{{ .SPOOLMAN_POSTGRES_USER }}"
        SPOOLMAN_DB_PASSWORD: &dbPass "{{ .SPOOLMAN_POSTGRES_PASS }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: spoolman
    - extract:
        key: cloudnative-pg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bambulab-spoolman
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bambulab-spoolman-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        printers.json: "{{ .BAMBULAB_PRINTERS }}"
  dataFrom:
    - extract:
        key: bambulab-spoolman
