---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lumo-tamer
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lumo-tamer-secret
    creationPolicy: Owner
    template:
      data:
        lumo-vault-key: "{{ .lumo_tamer_vault_key }}"
        config.yaml: |
          server:
            apiKey: "{{ .lumo_tamer_api_key }}"
            bodyLimit: "512kb"
            enableWebSearch: true
            customTools:
              enabled: true
  dataFrom:
    - extract:
        key: lumo-tamer
      rewrite:
        - regexp:
            source: "(.*)"
            target: "lumo_tamer_$1"
