services:
  factory:
    container_name: factory
    image: ghcr.io/siderolabs/image-factory:v1.4.0
    command:
      - /usr/bin/image-factory
      - --config
      - file=/config.yaml
    configs:
      - source: config
        target: /config.yaml
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ${DATA_DOCKER_DIR}/talos-factory/config:/config:ro
    tmpfs:
      - /tmp:mode=755,uid=1000,gid=1000
    networks:
      - apps
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.factory.loadbalancer.server.port=8080"
      - "traefik.http.routers.factory.rule=Host(`factory.codewalker.dev`)"
      - "traefik.http.routers.factory.entrypoints=websecure"
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    read_only: true

configs:
  config:
    file: ./config/config.yaml

networks:
  apps:
    name: apps
    external: true
