---
networks:
  apps:
    name: apps
    external: false

services:
  anubis:
    image: ghcr.io/techarohq/anubis:v1.27.0
    environment:
      BIND: ":9000"
      DIFFICULTY: "4"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://forgejo:3000"
      POLICY_FNAME: "/etc/anubis/policy.yaml"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    networks:
      - apps
    labels:
      - traefik.enable=true
      - traefik.http.routers.anubis-forgejo.rule=Host(`git.codewalker.dev`)
      - traefik.http.routers.anubis-forgejo.entrypoints=websecure
      - traefik.http.services.anubis-forgejo.loadbalancer.server.port=9000
    volumes:
      - ./anubis/policy.yaml:/etc/anubis/policy.yaml:ro

  forgejo:
    image: codeberg.org/forgejo/forgejo:16
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - apps
    ports:
      - "22:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: false
        source: /mnt/vmdata-ssd/container-data/forgejo
        target: /data
        type: bind
