---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: towonel-agent
spec:
  endpoints:
    - dnsName: ingress-ext.codewalker.dev
      recordType: A
      targets:
        - &vps_ip 141.227.131.76
    - dnsName: twnl.codewalker.dev
      recordType: A
      targets:
        - *vps_ip
    - dnsName: hyperdrive-doco-cd.codewalker.dev
      recordType: A
      targets:
        - *vps_ip
    - dnsName: hyperdrive-gatus.codewalker.dev
      recordType: A
      targets:
        - *vps_ip
