services:
  llama.cpp:
    container_name: llama.cpp
    image: ghcr.io/ggml-org/llama.cpp:server-cuda13
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /opt/llama/models:/root/.cache/huggingface
    restart: always
    environment:
      - LLAMA_ARG_N_GPU_LAYERS=999
    command:
      - "--models-preset"
      - "/config/config.ini"
    configs:
      - source: llamafile
        target: /config/config.ini
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.llama-cpp.loadbalancer.server.port=8080"
      - "traefik.http.routers.llama-cpp.rule=Host(`leia-qwen.codewalker.dev`)"
      - "traefik.http.routers.llama-cpp.entrypoints=websecure"

configs:
  llamafile:
    file: ./config/config.ini

networks:
  default:
    name: edge
    external: true
