---
originRequest:
  originServerName: external.erasit.nl

ingress:
  - hostname: erasit.nl
    service: &svc https://envoy-erasit.network.svc.cluster.local
  - hostname: "*.erasit.nl"
    service: *svc
  - service: http_status:404
