---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fastkoko
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: fastkoko
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      fastkoko:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/remsky/kokoro-fastapi-cpu
              tag: v0.8.0@sha256:d32322c61254a871e0bc9c38d4e60cd18539cf9b1a2fc8f3ae04409061d0793b
            resources:
              requests:
                cpu: 5m
                memory: 2Gi
              limits:
                memory: 4Gi
    service:
      app:
        controller: fastkoko
        ports:
          http:
            port: &port 8880

    route:
      app:
        hostnames: ["{{.Release.Name}}.codewalker.dev"]
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 404"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: "{{.Release.Name}}"
                port: *port

    persistence:
      tmp:
        type: emptyDir
