---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
spec:
  storageClassName: miroir-slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"
