---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-secret
    template:
      engineVersion: v2
      data:
        NTFY_TOKEN: "{{ .NTFY_USERS_GATUS_TOKEN }}"
        GATUS_HEARTBEAT_URL: "{{ .gatus_heartbeat_url }}"
  dataFrom:
    - extract:
        key: ntfy
    - extract:
        key: gatus
      rewrite:
        - regexp:
            source: "(.*)"
            target: "gatus_$1"
