---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: webhook-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Application
        GITHUB_WEBHOOK_SECRET: "{{ .GITHUB_WEBHOOK_SECRET }}"
  dataFrom:
    - extract:
        key: webhook
