---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rxresume
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rxresume-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Application
        DATABASE_URL: postgresql://{{ .RXRESUME_POSTGRES_USER }}:{{ .RXRESUME_POSTGRES_PASS }}@postgres-pgbouncer-rw.database.svc.cluster.local/rxresume
        STORAGE_BUCKET: "cluster-0-rxresume"
        STORAGE_ENDPOINT: minio.nnhome.eu
        STORAGE_PORT: "9000"
        STORAGE_REGION: us-east-1
        STORAGE_USE_SSL: "true"
        STORAGE_ACCESS_KEY: "{{ .RXRESUME_ACCESS_KEY }}"
        STORAGE_SECRET_KEY: "{{ .RXRESUME_SECRET_KEY }}"
        SMTP_URL: "{{ .RXRESUME_SMTP_URL }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: rxresume
        INIT_POSTGRES_HOST: postgres-pgbouncer-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .RXRESUME_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .RXRESUME_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: rxresume
    - extract:
        key: cloudnative-pg
