---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atuin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: atuin
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      atuin:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4
            envFrom:
              - secretRef:
                  name: atuin-secret
        containers:
          app:
            image:
              repository: ghcr.io/atuinsh/atuin
              tag: 18.19.0
            args:
              - start
            env:
              ATUIN_HOST: 0.0.0.0
              ATUIN_PORT: &port 8888
              ATUIN_OPEN_REGISTRATION: "true"
            envFrom:
              - secretRef:
                  name: atuin-secret
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                memory: 256Mi
    service:
      atuin:
        controller: atuin
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{.Release.Name}}.codewalker.dev"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: "{{.Release.Name}}"
                port: *port
    persistence:
      config:
        enabled: true
        type: emptyDir
