---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../components/common
resources:
  - ./atuin/ks.yaml
  - ./bichon/ks.yaml
  - ./fastkoko/ks.yaml
  - ./it-tools/ks.yaml
  - ./karakeep/ks.yaml
  - ./paperless/ks.yaml
  - ./rxresume/ks.yaml
  - ./searxng/ks.yaml
  - ./spoolman/ks.yaml
  - ./webhook/ks.yaml
  - ./wyoming/ks.yaml
  - ./zipline/ks.yaml
