loglevel = "ERROR"

[http]
  # Add the router
  [http.routers]
    [http.routers.adguard]
      entryPoints = ["websecure"]
      service = "adguard"
      rule = "Host(`dns.codewalker.dev`)"

  # Add the service
  [http.services]
    [http.services.adguard]
      [http.services.adguard.loadBalancer]
        [[http.services.adguard.loadBalancer.servers]]
          url = "http://172.16.20.9:3000/"
