################################################################
# File configuration backend
################################################################
# Enable file configuration backend
[file]
        filename = "servers.toml"

# Enable watch file changes
        watch = true
