---
services:
  mww-trainer:
    container_name: mww-trainer
    image: ghcr.io/tatertotterson/microwakeword:v29
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/mww-trainer/data:/data
    restart: always
    environment:
      - REC_PORT=8789
      - REC_PUBLIC_BASE_URL=https://leia-mww.codewalker.dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 8789:8789
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mww.loadbalancer.server.port=8789"
      - "traefik.http.routers.mww.rule=Host(`leia-mww.codewalker.dev`)"
      - "traefik.http.routers.mww.entrypoints=websecure"

networks:
  default:
    name: edge
    external: true
