---
endpoints:
  - name: healthchecks.io
    group: heartbeat
    url: ${GATUS_HEARTBEAT_URL}
    interval: 5m
    client:
      dns-resolver: tcp://9.9.9.9:53
    ui:
      hide-url: true
      hide-hostname: true
    conditions:
      - "[STATUS] == 200"
