---
endpoints:
  - name: hyperdrive | ping
    group: vps
    url: icmp://141.227.131.76
    interval: 1m
    ui:
      hide-url: true
      hide-hostname: true
    conditions:
      - "[CONNECTED] == true"
