---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ntfy-secret
    template:
      engineVersion: v2
      data:
        NTFY_AUTH_USERS: >-
          {{ .NTFY_USERS_ADMIN_USERNAME }}:{{ .NTFY_USERS_ADMIN_BCRYPT }}:admin,
          {{ .NTFY_USERS_GATUS_USERNAME }}:{{ .NTFY_USERS_GATUS_BCRYPT }}:user
        NTFY_AUTH_ACCESS: >-
          {{ .NTFY_USERS_GATUS_USERNAME }}:gatus*:read-write
        NTFY_AUTH_TOKENS: >-
          {{ .NTFY_USERS_GATUS_USERNAME }}:{{ .NTFY_USERS_GATUS_TOKEN }}
  dataFrom:
    - extract:
        key: ntfy
