---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: external.erasit.nl
      recordType: CNAME
      targets: ["db89b868-c2a0-4a39-8994-477eb2aefd7a.cfargotunnel.com"]
