[*]

; Set Chat Template
jinja = true

; GPU Performance
n-gpu-layers = -1
flash-attn = on
fit = off

; Overall Performance
prio = 3
prio-batch = 3

; Increased Batch Size
batch-size = 2048
ubatch-size = 2048

; Set reasonable max thinking budgets
reasoning-budget-message = '... Taking too long, need to answer.'


[byteshape/Qwen3.5-9B-GGUF:Qwen3.5-9B-IQ4_XS-4.20bpw]

; Alias
alias = Qwen3.5

; Model Name
hf = byteshape/Qwen3.5-9B-GGUF:Qwen3.5-9B-IQ4_XS-4.20bpw

; Tuning
temp = 0.7
top-p = 0.8
top-k = 20
min-p = 0.00
presence-penalty = 1.5
repeat-penalty = 1

; Context Size
ctx-size = 32768
parallel = 4
cache-idle-slots = off
kvu = on
cache-ram = 4096

reasoning = off

; Model Load Behavior
load-on-startup = true
