---
networks:
  apps:
    name: apps
    external: false

services:
  anubis:
    image: ghcr.io/techarohq/anubis:v1.25.0
    environment:
      BIND: ":9000"
      DIFFICULTY: "4"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://downloader:8080"
      POLICY_FNAME: "/etc/anubis/policy.yaml"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    networks:
      - apps
    labels:
      - traefik.enable=true
      - traefik.http.routers.anubis-downloader.rule=Host(`downloader.codewalker.dev`)
      - traefik.http.routers.anubis-downloader.entrypoints=websecure
      - traefik.http.services.anubis-downloader.loadbalancer.server.port=9000
    volumes:
      - ./anubis/policy.yaml:/etc/anubis/policy.yaml:ro

  downloader:
    image: git.codewalker.dev/mavy/docker-downloader:0.1.0
    container_name: downloader
    restart: always
    networks:
      - apps
    environment:
      PASSPHRASE: ${DOWNLOADER_PASSPHRASE}
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.services.downloader.loadbalancer.server.port=8080"
    #   - "traefik.http.routers.downloader.rule=Host(`downloader.codewalker.dev`)"
    #   - "traefik.http.routers.downloader.entrypoints=websecure"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: false
        source: /mnt/vmdata-ssd/container-data/downloader
        target: /out
        type: bind
