networks:
  apps:
    name: apps
    external: false

services:
  anubis:
    image: ghcr.io/techarohq/anubis:v1.25.0
    environment:
      - BIND=":9000"
      - DIFFICULTY="4"
      - SERVE_ROBOTS_TXT="true"
      - TARGET="http://downloader:8080"
      - POLICY_FNAME="/etc/anubis/policy.yaml"
      - OG_PASSTHROUGH="true"
      - OG_EXPIRY_TIME="24h"
    networks:
      - apps
    labels:
      - traefik.enable=true
      - traefik.http.routers.anubis.rule=Host(`downloader.codewalker.dev`)
      - traefik.http.routers.anubis.entrypoints=websecure
      - traefik.http.services.anubis.loadbalancer.server.port=9000

  downloader:
    image: git.codewalker.dev/mavy/docker-downloader:0.1.0
    container_name: downloader
    restart: always
    networks:
      - apps
    ports:
      - '8080:8080'
    environment:
      - PASSPHRASE=${DOWNLOADER_PASSPHRASE}
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.services.downloader.loadbalancer.server.port=8080"
    #   - "traefik.http.routers.downloader.rule=Host(`downloader.codewalker.dev`)"
    #   - "traefik.http.routers.downloader.entrypoints=websecure"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/vmdata-ssd/container-data/downloader
        target: /out
        type: bind
