---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliumcidrgroup_v2.json
apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: holocron
spec:
  externalCIDRs:
    - 172.16.20.2/32
